lowdown: use ports-gcc on base-gcc
base-gcc doesn't support deprecated attributes with deprecation message.
ports-gcc is lower friction than patching the header:

lowdown.h:460: error: wrong number of arguments specified for 'deprecated' attribute